version: '2'

services:
  bitdb:
    build:
      context: .
      dockerfile: ./containers/bitdb/Dockerfile
    ports:
      - "5555:30303"
    links:
      - 'bch'
    stdin_open: true
    tty: true

  bch:
    build:
      context: .
      dockerfile: ./containers/bch/Dockerfile
    command: /usr/bin/bitcoind --printtoconsole
    volumes:
      - './containers/bch/data:/root/.bch'
    ports:
      - "5556:18332"
      - "28332:28332"
    stdin_open: true
    tty: true

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      -  'MONGODB_USER=user'
      -  'MONGODB_PASS=password!'
    volumes:
      - './containers/mongodb/data:/data/db'
    ports:
      - '27017:27017'
    command: mongod --smallfiles

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    links:
      - 'mongodb:mongo'
    ports:
      - '8081:8081'
    environment:
      - 'ME_CONFIG_OPTIONS_EDITORTHEME=ambiance'
      - 'ME_CONFIG_BASICAUTH_USERNAME=user'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=password!'

  # Grafana : http://localhost:3000/
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - './containers/grafana/data:/var/lib/grafana'